### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by aaannndddyyy** [macourtney/masques#57]

**Comment by macourtney** [comment]
I can't really work on it right now, but I will accept pull requests.

**Comment by aaannndddyyy** [comment]
Ok, it's good to know you have not abandoned it for good. 
"right now" implies at least that there is a chance you can do it in the future.
I cannot code, unfortunatelly, so no code contributions from me. Sorry. 
But I think this is a very interesting project. Would love to see it work out.
